language: node_js
node_js:
  - node

script:
- yarn run flow init
- yarn run flow ls --strip-root
- yarn run flow

after_script:
- ls --color node_modules/.bin
- yarn run flow init --help
- yarn run flow --help
