language: node_js
node_js:
  - node

script:
- yarn run flow init
- yarn run flow ls --strip-root
- yarn run flow
- yarn run babel src/ -- -d lib/

after_script:
- ls --color
- ls --color --recursive lib
- ls --color node_modules/.bin
- yarn run flow init --help
- yarn run flow --help
- yarn run --help
- yarn exec --help
- yarn --help
