language: node_js
node_js:
  - node

script:
- yarn run flow init
- yarn run flow
- npm run build

after_script:
- npm run
- yarn run flow ls --strip-root
- ls --color
- ls --color --recursive lib
- cat lib/foo.js
- ls --color node_modules/.bin
- yarn run babel --help
- yarn run flow init --help
- yarn run flow --help
- yarn run --help
- yarn exec --help
- yarn --help
