language: node_js
node_js:
  - node

script:
- yarn run flow init
- yarn run flow
- npm run build
- yarn run babel src/ -- -d lib/
- yarn run babel src/ -d lib/

after_script:
- npm run
- yarn run flow ls --strip-root
- ls --color
- ls --color --recursive lib
- ls --color node_modules/.bin
- yarn run babel --help
- yarn run babel
- yarn run flow init --help
- yarn run flow --help
- yarn run --help
- yarn exec --help
- yarn --help
